"use client";

import { useState, useRef, useCallback } from "react";
import { generateHarmonyColors, normalizeHex, HARMONY_MODES } from "@/lib/colorUtils";
import type { HarmonyMode } from "@/lib/colorUtils";

export interface ManualRoles {
  primary: string;
  secondary: string;
  tertiary: string;
  accent: string;
}

interface Props {
  onImageUpload: (file: File, previewUrl: string) => void;
  onManualGenerate: (roles: ManualRoles, explicitKeys: (keyof ManualRoles)[], mode: HarmonyMode) => void;
  isLoading?: boolean;
  error?: string | null;
  onErrorDismiss?: () => void;
}

const ACCEPTED = ["image/jpeg", "image/png", "image/webp", "image/gif", "image/avif"];
const ROLE_LABELS: (keyof ManualRoles)[] = ["primary", "secondary", "tertiary", "accent"];

function isValidHex(v: string) {
  return /^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/.test(v.trim());
}

/** Visual preview of a hex (returns neutral gray if empty/invalid) */
function previewColor(v: string) {
  return v && isValidHex(v) ? normalizeHex(v) : "#e8e8e4";
}

export default function SplitHomepage({
  onImageUpload, onManualGenerate, isLoading, error, onErrorDismiss
}: Props) {
  const [isDragging, setIsDragging] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);
  const [harmonyMode, setHarmonyMode] = useState<HarmonyMode>("split-complementary");

  // All optional — only primary is required. Empty = auto-generate from primary.
  const [fields, setFields] = useState<Record<keyof ManualRoles, string>>({
    primary:   "",
    secondary: "",
    tertiary:  "",
    accent:    "",
  });
  const [formError, setFormError] = useState("");

  const setField = (key: keyof ManualRoles, val: string) => {
    setFields((f) => ({ ...f, [key]: val }));
    if (formError) setFormError("");
  };

  const processFile = useCallback(
    (file: File) => {
      if (!ACCEPTED.includes(file.type)) {
        alert("Unsupported format. Please use JPG, PNG, WEBP, GIF, or AVIF.");
        return;
      }
      onImageUpload(file, URL.createObjectURL(file));
    },
    [onImageUpload]
  );

  const onDrop = useCallback(
    (e: React.DragEvent) => {
      e.preventDefault();
      setIsDragging(false);
      const file = e.dataTransfer.files[0];
      if (file) processFile(file);
    },
    [processFile]
  );

  const handleGenerate = () => {
    const primaryVal = fields.primary.trim();

    if (!primaryVal) {
      setFormError("Primary color is required");
      return;
    }
    if (!isValidHex(primaryVal)) {
      setFormError("Primary must be a valid hex — e.g. #6366f1");
      return;
    }

    const primary = normalizeHex(primaryVal);

    // Determine which fields are explicitly filled
    const explicitKeys: (keyof ManualRoles)[] = ["primary"];
    const secondary = fields.secondary && isValidHex(fields.secondary)
      ? normalizeHex(fields.secondary)
      : null;
    const tertiary = fields.tertiary && isValidHex(fields.tertiary)
      ? normalizeHex(fields.tertiary)
      : null;
    const accent = fields.accent && isValidHex(fields.accent)
      ? normalizeHex(fields.accent)
      : null;

    if (secondary) explicitKeys.push("secondary");
    if (tertiary)  explicitKeys.push("tertiary");
    if (accent)    explicitKeys.push("accent");

    // Auto-fill from primary for any missing
    const generated = generateHarmonyColors(primary, harmonyMode);

    const roles: ManualRoles = {
      primary,
      secondary: secondary ?? generated.secondary,
      tertiary:  tertiary  ?? generated.tertiary,
      accent:    accent    ?? generated.accent,
    };

    setFormError("");
    onManualGenerate(roles, explicitKeys, harmonyMode);
  };

  // Live preview: if primary is valid, preview harmony colors for empty slots
  const primaryValid = fields.primary && isValidHex(fields.primary);
  const generated = primaryValid ? generateHarmonyColors(normalizeHex(fields.primary), harmonyMode) : null;

  const getSwatchColor = (role: keyof ManualRoles): string => {
    const val = fields[role];
    if (val && isValidHex(val)) return normalizeHex(val);
    if (generated && role !== "primary") return generated[role as keyof typeof generated];
    return "#e8e8e4";
  };

  const isAutoGenerated = (role: keyof ManualRoles): boolean => {
    if (role === "primary") return false;
    return !!(generated && (!fields[role] || !isValidHex(fields[role])));
  };

  return (
    <div className="flex flex-col" style={{ minHeight: "100svh" }}>

      {/* ── Top bar ── */}
      <div className="border-b-2 border-[#0a0a0a] px-8 md:px-12 py-5 flex items-center justify-between shrink-0">
        <div className="flex items-center gap-3">
          <div className="w-3.5 h-3.5 bg-[#0a0a0a]" />
          <span className="font-mono text-[12px] uppercase tracking-[0.35em] text-[#0a0a0a]">
            Design System Generator
          </span>
        </div>
        <span className="font-mono text-[12px] uppercase tracking-[0.3em] text-[#bbb] hidden sm:block">
          Generate · Export · Use
        </span>
      </div>

      {/* ── Error banner ── */}
      {error && (
        <div className="border-b border-[#dc2626] bg-[#fef2f2] px-8 md:px-12 py-3 flex items-center justify-between shrink-0">
          <span className="font-mono text-[12px] text-[#dc2626]">{error}</span>
          <button onClick={onErrorDismiss} className="font-mono text-[12px] text-[#dc2626] hover:underline">
            Dismiss
          </button>
        </div>
      )}

      {/* ── Loading strip ── */}
      {isLoading && (
        <div className="border-b border-[#0a0a0a] px-8 md:px-12 py-3 flex items-center gap-4 shrink-0">
          <div className="flex gap-1">
            {[0, 1, 2, 3, 4].map((i) => (
              <div
                key={i}
                className="w-5 h-5 bg-[#0a0a0a]"
                style={{ animation: `gridPulse 1s ease-in-out ${i * 0.12}s infinite` }}
              />
            ))}
          </div>
          <span className="font-mono text-[12px] uppercase tracking-widest text-[#888]">
            Analyzing pixel data…
          </span>
        </div>
      )}

      {/* ── Main split ── */}
      <div className="flex-1 grid grid-cols-1 md:grid-cols-2 divide-y-2 md:divide-y-0 md:divide-x-2 divide-[#0a0a0a]">

        {/* ── LEFT: Image upload ── */}
        <div
          className={`relative flex flex-col cursor-crosshair select-none min-h-[60vmin] md:min-h-0 transition-colors duration-150 ${
            isDragging ? "bg-[#f0f0ec]" : "hover:bg-[#f5f5f3]"
          }`}
          onDrop={onDrop}
          onDragOver={(e) => { e.preventDefault(); setIsDragging(true); }}
          onDragLeave={() => setIsDragging(false)}
          onClick={() => !isLoading && inputRef.current?.click()}
        >
          {/* Corner marks */}
          <div className="absolute inset-0 pointer-events-none" aria-hidden>
            <div className="absolute top-8 left-8 w-5 h-5 border-t-2 border-l-2 border-[#0a0a0a] opacity-30" />
            <div className="absolute top-8 right-8 w-5 h-5 border-t-2 border-r-2 border-[#0a0a0a] opacity-30" />
            <div className="absolute bottom-8 left-8 w-5 h-5 border-b-2 border-l-2 border-[#0a0a0a] opacity-30" />
            <div className="absolute bottom-8 right-8 w-5 h-5 border-b-2 border-r-2 border-[#0a0a0a] opacity-30" />
          </div>

          <div className="relative flex flex-col h-full p-10 md:p-14 lg:p-20">
            <div className="flex items-start justify-between">
              <span className="font-mono text-[12px] uppercase tracking-[0.5em] text-[#aaa]">01</span>
              <div className="flex gap-4">
                {["JPG", "PNG", "WEBP", "GIF"].map((f) => (
                  <span key={f} className="font-mono text-[12px] uppercase tracking-widest text-[#ccc]">{f}</span>
                ))}
              </div>
            </div>

            <div className="py-12 md:py-16">
              <h2 className="font-black text-[clamp(3rem,7vw,5.5rem)] uppercase leading-[0.86] tracking-tighter text-[#0a0a0a]">
                {isDragging ? "Release →" : <span>From<br />Image</span>}
              </h2>
            </div>

            <div
              className={`relative flex flex-col items-center justify-center border-2 border-dashed border-[#0a0a0a] min-h-[42vmin] md:min-h-[280px] transition-colors duration-150 ${
                isDragging ? "bg-[#f0f0ec]" : ""
              }`}
            >
              <div className="border-2 border-[#0a0a0a] w-14 h-14 flex items-center justify-center mb-8">
                <svg width="20" height="20" viewBox="0 0 18 18" fill="none">
                  <path d="M9 13V4M9 4L5 8M9 4l4 4" stroke="currentColor" strokeWidth="1.5"/>
                  <path d="M2.5 15h13" stroke="currentColor" strokeWidth="1.5"/>
                </svg>
              </div>

              <p className="font-black text-xl uppercase tracking-tight">
                Drop Image Here
              </p>

              <p className="font-mono text-[12px] uppercase tracking-[0.25em] text-[#999] mt-3">
                Or Click Anywhere To Browse
              </p>

              <p className="font-mono text-[12px] uppercase tracking-[0.35em] text-[#bbb] mt-5">
                JPG · PNG · WEBP · GIF · AVIF · max 10 MB
              </p>
            </div>
          </div>

          <input
            ref={inputRef}
            type="file"
            accept={ACCEPTED.join(",")}
            onChange={(e) => { const f = e.target.files?.[0]; if (f) processFile(f); }}
            className="hidden"
          />
        </div>

        {/* ── RIGHT: Brand Colors ── */}
        <div className="flex flex-col p-10 md:p-14 lg:p-20 min-h-[60vmin] md:min-h-0">
          <span className="font-mono text-[12px] uppercase tracking-[0.5em] text-[#aaa]">02</span>

          <div className="py-12 md:py-16">
            <h2 className="font-black text-[clamp(3rem,7vw,5.5rem)] uppercase leading-[0.86] tracking-tighter text-[#0a0a0a]">
              From<br />Brand<br />Colors
            </h2>
          </div>

          {/* Harmony mode picker */}
          <div className="mb-8">
            <p className="font-mono text-[12px] uppercase tracking-[0.4em] text-[#aaa] mb-3">
              Color Harmony
            </p>
            <div className="flex flex-wrap gap-1.5">
              {HARMONY_MODES.map((mode) => (
                <button
                  key={mode.id}
                  onClick={() => setHarmonyMode(mode.id)}
                  className="font-mono text-[12px] uppercase tracking-[0.2em] px-3 py-1.5 transition-all"
                  style={{
                    backgroundColor: harmonyMode === mode.id ? "#0a0a0a" : "transparent",
                    color: harmonyMode === mode.id ? "#f9f9f7" : "#888",
                    border: harmonyMode === mode.id ? "1px solid #0a0a0a" : "1px solid #e8e8e4",
                  }}
                  title={mode.label}
                >
                  {mode.short}
                </button>
              ))}
            </div>
            {primaryValid && generated && (
              <div className="flex gap-1.5 mt-3">
                {["primary", "secondary", "tertiary", "accent"].map((role) => {
                  const val = role === "primary"
                    ? normalizeHex(fields.primary)
                    : generated[role as keyof typeof generated];
                  return (
                    <div
                      key={role}
                      className="flex-1 h-3"
                      style={{ backgroundColor: val }}
                      title={`${role}: ${val}`}
                    />
                  );
                })}
              </div>
            )}
          </div>

          {/* Color inputs */}
          <div className="space-y-7 mb-10">
            {ROLE_LABELS.map((role) => {
              const auto = isAutoGenerated(role);
              const swatchColor = getSwatchColor(role);
              return (
                <div key={role} className="flex items-center gap-5">
                  {/* Label */}
                  <div className="min-w-[80px]">
                    <span className="font-mono text-[12px] uppercase tracking-[0.3em] text-[#888]">
                      {role}
                    </span>
                    {role !== "primary" && (
                      <span className="font-mono text-[12px] block text-[#bbb] mt-0.5">
                        {auto ? "auto" : "custom"}
                      </span>
                    )}
                    {role === "primary" && (
                      <span className="font-mono text-[12px] block text-[#dc2626] mt-0.5">required</span>
                    )}
                  </div>

                  {/* Swatch + native picker */}
                  <div className="relative w-8 h-8 shrink-0">
                    <div
                      className="w-8 h-8 border border-[#d8d8d4] transition-colors"
                      style={{ backgroundColor: swatchColor, opacity: auto ? 0.5 : 1 }}
                    />
                    <input
                      type="color"
                      value={isValidHex(fields[role]) ? normalizeHex(fields[role]) : "#6366f1"}
                      onChange={(e) => setField(role, e.target.value)}
                      className="absolute inset-0 opacity-0 cursor-pointer w-full h-full"
                    />
                  </div>

                  {/* Hex text input */}
                  <input
                    type="text"
                    value={fields[role]}
                    onChange={(e) => setField(role, e.target.value)}
                    placeholder={
                      auto && generated
                        ? generated[role as keyof typeof generated]
                        : role === "primary" ? "#6366f1" : "optional"
                    }
                    className="flex-1 font-mono text-[12px] text-[#0a0a0a] bg-transparent border-b-2 border-[#e8e8e4] pb-2 outline-none focus:border-[#0a0a0a] transition-colors placeholder-[#ccc] max-w-[150px]"
                  />
                </div>
              );
            })}

            {formError && (
              <p className="font-mono text-[12px] text-[#dc2626] pt-1">{formError}</p>
            )}

            {primaryValid && (
              <p className="font-mono text-[12px] text-[#aaa] leading-relaxed pt-1">
                Secondary, Tertiary and Accent auto-generated from Primary if left blank.
              </p>
            )}
          </div>

          {/* CTA */}
          <div className="mt-auto">
            <button
              onClick={handleGenerate}
              disabled={isLoading}
              className="font-mono text-[12px] uppercase tracking-[0.2em] bg-[#0a0a0a] text-white px-10 py-4 hover:bg-[#1a1a1a] active:bg-[#333] transition-colors disabled:opacity-40"
            >
              Generate System →
            </button>
          </div>
        </div>
      </div>

      {/* ── Bottom bar ── */}
      <div className="border-t-2 border-[#0a0a0a] px-8 md:px-12 py-4 flex items-center justify-between shrink-0">
        <p className="font-mono text-[12px] uppercase tracking-[0.3em] text-[#bbb]">
          Colors · Typography · Spacing · Radius · Shadows · Components · WCAG · CSS / Tailwind / Figma
        </p>
        <p className="font-mono text-[12px] uppercase tracking-[0.3em] text-[#bbb] hidden sm:block">
          Janvi Guliyan · {new Date().getFullYear()}
        </p>
      </div>
    </div>
  );
}
