"use client";

import { useState, useRef, useCallback } from "react";
import { generateHarmoniousColors, normalizeHex } from "@/lib/colorUtils";

export interface ManualRoles {
  primary: string;
  secondary: string;
  tertiary: string;
  accent: string;
}

interface Props {
  onImageUpload: (file: File, previewUrl: string) => void;
  onManualGenerate: (roles: ManualRoles, explicitKeys: (keyof ManualRoles)[]) => void;
  isLoading?: boolean;
  error?: string | null;
  onErrorDismiss?: () => void;
}

const ACCEPTED = ["image/jpeg", "image/png", "image/webp", "image/gif", "image/avif"];
const ROLE_LABELS: (keyof ManualRoles)[] = ["primary", "secondary", "tertiary", "accent"];

function isValidHex(v: string) {
  return /^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/.test(v.trim());
}

/** Visual preview of a hex (returns neutral gray if empty/invalid) */
function previewColor(v: string) {
  return v && isValidHex(v) ? normalizeHex(v) : "#e8e8e4";
}

export default function SplitHomepage({
  onImageUpload, onManualGenerate, isLoading, error, onErrorDismiss
}: Props) {
  const [isDragging, setIsDragging] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);

  // All optional — only primary is required. Empty = auto-generate from primary.
  const [fields, setFields] = useState<Record<keyof ManualRoles, string>>({
    primary:   "",
    secondary: "",
    tertiary:  "",
    accent:    "",
  });
  const [formError, setFormError] = useState("");

  const setField = (key: keyof ManualRoles, val: string) => {
    setFields((f) => ({ ...f, [key]: val }));
    if (formError) setFormError("");
  };

  const processFile = useCallback(
    (file: File) => {
      if (!ACCEPTED.includes(file.type)) {
        alert("Unsupported format. Please use JPG, PNG, WEBP, GIF, or AVIF.");
        return;
      }
      onImageUpload(file, URL.createObjectURL(file));
    },
    [onImageUpload]
  );

  const onDrop = useCallback(
    (e: React.DragEvent) => {
      e.preventDefault();
      setIsDragging(false);
      const file = e.dataTransfer.files[0];
      if (file) processFile(file);
    },
    [processFile]
  );

  const handleGenerate = () => {
    const primaryVal = fields.primary.trim();

    if (!primaryVal) {
      setFormError("Primary color is required");
      return;
    }
    if (!isValidHex(primaryVal)) {
      setFormError("Primary must be a valid hex — e.g. #6366f1");
      return;
    }

    const primary = normalizeHex(primaryVal);

    // Determine which fields are explicitly filled
    const explicitKeys: (keyof ManualRoles)[] = ["primary"];
    const secondary = fields.secondary && isValidHex(fields.secondary)
      ? normalizeHex(fields.secondary)
      : null;
    const tertiary = fields.tertiary && isValidHex(fields.tertiary)
      ? normalizeHex(fields.tertiary)
      : null;
    const accent = fields.accent && isValidHex(fields.accent)
      ? normalizeHex(fields.accent)
      : null;

    if (secondary) explicitKeys.push("secondary");
    if (tertiary)  explicitKeys.push("tertiary");
    if (accent)    explicitKeys.push("accent");

    // Auto-fill from primary for any missing
    const generated = generateHarmoniousColors(primary);

    const roles: ManualRoles = {
      primary,
      secondary: secondary ?? generated.secondary,
      tertiary:  tertiary  ?? generated.tertiary,
      accent:    accent    ?? generated.accent,
    };

    setFormError("");
    onManualGenerate(roles, explicitKeys);
  };

  // Live preview: if primary is valid, preview harmonious colors for empty slots
  const primaryValid = fields.primary && isValidHex(fields.primary);
  const generated = primaryValid ? generateHarmoniousColors(normalizeHex(fields.primary)) : null;

  const getSwatchColor = (role: keyof ManualRoles): string => {
    const val = fields[role];
    if (val && isValidHex(val)) return normalizeHex(val);
    if (generated && role !== "primary") return generated[role as keyof typeof generated];
    return "#e8e8e4";
  };

  const isAutoGenerated = (role: keyof ManualRoles): boolean => {
    if (role === "primary") return false;
    return !!(generated && (!fields[role] || !isValidHex(fields[role])));
  };

  return (
    <div className="flex flex-col" style={{ minHeight: "100svh" }}>

      {/* ── Slim top bar ── */}
      <div className="border-b border-[#0a0a0a] px-8 md:px-12 py-3.5 flex items-center justify-between shrink-0">
        <div className="flex items-center gap-2.5">
          <div className="w-3 h-3 bg-[#0a0a0a]" />
          <span className="font-mono text-[10px] uppercase tracking-[0.35em] text-[#0a0a0a]">
            Design System Generator
          </span>
        </div>
        <span className="font-mono text-[9px] uppercase tracking-[0.25em] text-[#bbb] hidden sm:block">
          Generate · Export · Use
        </span>
      </div>

      {/* ── Error banner ── */}
      {error && (
        <div className="border-b border-[#dc2626] bg-[#fef2f2] px-8 md:px-12 py-3 flex items-center justify-between shrink-0">
          <span className="font-mono text-[10px] text-[#dc2626]">{error}</span>
          <button onClick={onErrorDismiss} className="font-mono text-[9px] text-[#dc2626] hover:underline">
            Dismiss
          </button>
        </div>
      )}

      {/* ── Loading strip ── */}
      {isLoading && (
        <div className="border-b border-[#0a0a0a] px-8 md:px-12 py-3 flex items-center gap-4 shrink-0">
          <div className="flex gap-1">
            {[0, 1, 2, 3, 4].map((i) => (
              <div
                key={i}
                className="w-5 h-5 bg-[#0a0a0a]"
                style={{ animation: `gridPulse 1s ease-in-out ${i * 0.12}s infinite` }}
              />
            ))}
          </div>
          <span className="font-mono text-[10px] uppercase tracking-widest text-[#888]">
            Analyzing pixel data…
          </span>
        </div>
      )}

      {/* ── Main split ── */}
      <div className="flex-1 grid grid-cols-1 md:grid-cols-2 divide-y-2 md:divide-y-0 md:divide-x-2 divide-[#0a0a0a]">

        {/* ── LEFT: Image upload ── */}
        <div
          className={`relative flex flex-col cursor-crosshair select-none min-h-[55vmin] md:min-h-0 transition-colors duration-150 ${
            isDragging ? "bg-[#f0f0ec]" : "hover:bg-[#f5f5f3]"
          }`}
          onDrop={onDrop}
          onDragOver={(e) => { e.preventDefault(); setIsDragging(true); }}
          onDragLeave={() => setIsDragging(false)}
          onClick={() => !isLoading && inputRef.current?.click()}
        >
          {/* Subtle crosshairs */}
          <div className="absolute inset-0 pointer-events-none" aria-hidden>
            <div className="absolute top-1/2 left-0 right-0 h-px bg-[#0a0a0a] opacity-[0.04]" />
            <div className="absolute left-1/2 top-0 bottom-0 w-px bg-[#0a0a0a] opacity-[0.04]" />
            {/* {["top-8 left-8", "top-8 right-8", "bottom-8 left-8", "bottom-8 right-8"].map((pos) => (
              <div key={pos} className={`absolute ${pos} w-6 h-6 opacity-10`}>
                <div className="absolute top-0 left-0 w-full h-px bg-[#0a0a0a]" />
                <div className="absolute top-0 left-0 h-full w-px bg-[#0a0a0a]" />
              </div>
            ))} */}
            {/* top-left */}
            <div className="absolute top-8 left-8 w-6 h-6 border-t border-l border-black opacity-40" />
            {/* top-right */}
            <div className="absolute top-8 right-8 w-6 h-6 border-t border-r border-black opacity-40" />
            {/* bottom-left */}
            <div className="absolute bottom-8 left-8 w-6 h-6 border-b border-l border-black opacity-40" />
            {/* bottom-right */}
            <div className="absolute bottom-8 right-8 w-6 h-6 border-b border-r border-black opacity-40" />
          </div>

          <div className="relative flex flex-col h-full p-8 md:p-12 lg:p-16">
            <div className="flex items-start justify-between mb-1">
              <span className="font-mono text-[9px] uppercase tracking-[0.5em] text-[#aaa]">01</span>
              <div className="flex gap-4">
                {["JPG", "PNG", "WEBP", "GIF"].map((f) => (
                  <span key={f} className="font-mono text-[8px] uppercase tracking-widest text-[#ccc]">{f}</span>
                ))}
              </div>
            </div>

            <div className="py-10 md:py-14">
              <h2 className="font-black text-[clamp(3rem,7vw,5.5rem)] uppercase leading-[0.86] tracking-tighter text-[#0a0a0a]">
                {isDragging ? "Release →" : <span>From<br />Image</span>}
              </h2>
            </div>

            <div
              className={`relative flex flex-col items-center justify-center border-2 border-dashed border-[#0a0a0a] h-[38vmin] transition-colors duration-150 ${
                isDragging ? "bg-[#f0f0ec]" : "hover:bg-[#f5f5f3]"
              }`}
            >
              
              <div className="border-2 border-[#0a0a0a] w-12 h-12 flex items-center justify-center mb-6">
                <svg width="18" height="18" viewBox="0 0 18 18" fill="none">
                  <path d="M9 13V4M9 4L5 8M9 4l4 4" stroke="currentColor" strokeWidth="1.5"/>
                  <path d="M2.5 15h13" stroke="currentColor" strokeWidth="1.5"/>
                </svg>
              </div>

              <p className="font-bold text-xl uppercase tracking-tight">
                Drop Image Here
              </p>

              <p className="font-mono text-[10px] uppercase tracking-[0.25em] text-[#999] mt-2">
                Or Click Anywhere To Browse
              </p>

              <p className="font-mono text-[9px] uppercase tracking-[0.35em] text-[#bbb] mt-4">
                JPG | PNG | WEBP | GIF | AVIF · MAX 10MB
              </p>

            </div>

            {/* <div className="flex items-end justify-between mt-auto">
              <div>
                <p className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#555] mb-1">
                  {isDragging ? "Drop to analyze" : "Drop or click to upload"}
                </p>
                <p className="font-mono text-[8px] uppercase tracking-widest text-[#bbb]">
                  K-Means · Max 10 MB
                </p>
              </div>
              <div className={`border-2 border-[#0a0a0a] w-11 h-11 flex items-center justify-center transition-all ${isDragging ? "bg-[#0a0a0a]" : ""}`}>
                <svg width="18" height="18" viewBox="0 0 18 18" fill="none" className={isDragging ? "text-white" : "text-[#0a0a0a]"}>
                  <path d="M9 13V4M9 4L5 8M9 4l4 4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="square" />
                  <path d="M2.5 15h13" stroke="currentColor" strokeWidth="1.5" strokeLinecap="square" />
                </svg>
              </div>
            </div> */}
          </div>

          <input
            ref={inputRef}
            type="file"
            accept={ACCEPTED.join(",")}
            onChange={(e) => { const f = e.target.files?.[0]; if (f) processFile(f); }}
            className="hidden"
          />
        </div>

        {/* ── RIGHT: Brand Colors ── */}
        <div className="flex flex-col p-8 md:p-12 lg:p-16 min-h-[55vmin] md:min-h-0">
          <span className="font-mono text-[9px] uppercase tracking-[0.5em] text-[#aaa] mb-1">02</span>

          <div className="py-10 md:py-14">
            <h2 className="font-black text-[clamp(3rem,7vw,5.5rem)] uppercase leading-[0.86] tracking-tighter text-[#0a0a0a]">
              From<br />Brand<br />Colors
            </h2>
          </div>

          {/* Color inputs */}
          <div className="space-y-5 mb-8">
            {ROLE_LABELS.map((role) => {
              const auto = isAutoGenerated(role);
              const swatchColor = getSwatchColor(role);
              return (
                <div key={role} className="flex items-center gap-4">
                  {/* Label */}
                  <div className="min-w-[72px]">
                    <span className="font-mono text-[9px] uppercase tracking-[0.3em] text-[#888]">
                      {role}
                    </span>
                    {role !== "primary" && (
                      <span className="font-mono text-[7px] block text-[#bbb] mt-0.5">
                        {auto ? "auto" : "custom"}
                      </span>
                    )}
                    {role === "primary" && (
                      <span className="font-mono text-[7px] block text-[#dc2626] mt-0.5">required</span>
                    )}
                  </div>

                  {/* Swatch + native picker */}
                  <div className="relative w-7 h-7 shrink-0">
                    <div
                      className="w-7 h-7 border border-[#d8d8d4] transition-colors"
                      style={{ backgroundColor: swatchColor, opacity: auto ? 0.5 : 1 }}
                    />
                    <input
                      type="color"
                      value={isValidHex(fields[role]) ? normalizeHex(fields[role]) : "#6366f1"}
                      onChange={(e) => setField(role, e.target.value)}
                      className="absolute inset-0 opacity-0 cursor-pointer w-full h-full"
                    />
                  </div>

                  {/* Hex text input */}
                  <input
                    type="text"
                    value={fields[role]}
                    onChange={(e) => setField(role, e.target.value)}
                    placeholder={
                      auto && generated
                        ? generated[role as keyof typeof generated]
                        : role === "primary" ? "#6366f1" : "optional"
                    }
                    className="flex-1 font-mono text-[11px] text-[#0a0a0a] bg-transparent border-b border-[#e8e8e4] pb-1.5 outline-none focus:border-[#0a0a0a] transition-colors placeholder-[#ccc] max-w-[140px]"
                  />
                </div>
              );
            })}

            {formError && (
              <p className="font-mono text-[9px] text-[#dc2626]">{formError}</p>
            )}

            {primaryValid && (
              <p className="font-mono text-[8px] text-[#aaa] leading-relaxed">
                Secondary, Tertiary and Accent will be auto-generated from Primary if left blank.
              </p>
            )}
          </div>

          {/* CTA */}
          <div className="mt-auto">
            <button
              onClick={handleGenerate}
              disabled={isLoading}
              className="font-mono text-[10px] uppercase tracking-widest bg-[#0a0a0a] text-white px-8 py-3.5 hover:bg-[#1a1a1a] active:bg-[#333] transition-colors disabled:opacity-40"
            >
              Generate System →
            </button>
          </div>
        </div>
      </div>

      {/* ── Bottom bar ── */}
      <div className="border-t border-[#0a0a0a] px-8 md:px-12 py-3 flex items-center justify-between shrink-0">
        <p className="font-mono text-[8px] uppercase tracking-widest text-[#ccc]">
          50–900 Scales · Neutral Greys · Semantic Colors · WCAG · CSS / Tailwind / Figma
        </p>
        <p className="font-mono text-[8px] uppercase tracking-widest text-[#ccc] hidden sm:block">
          Janvi Guliyan, {new Date().getFullYear()}
        </p>
      </div>
    </div>
  );
}
